services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: db
      MYSQL_USER: admin              
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: app
    ports:
      - "3030:3030"
    depends_on:
      db:
        condition: service_healthy
volumes:
  mysql_data: